FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o main .

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/main .
COPY --from=builder /app/.env .

# Copy templates
COPY --from=builder /app/email-templates ./email-templates

EXPOSE 4000

CMD ["./main"]
